# file: plots.R
# author: AJ
# twitter: dataparadigms
# web: http://www.dataparadigms.com
#
# description:
#   generates plots of the possible next pope based on the 
#   odds generated by one of the leading internet book makers

require('ggplot2')
require('scales')
require('lubridate')

data <- read.csv("odds.csv", 
  header = FALSE,
  as.is = TRUE)

# clean up
colnames(data) <- c('date', 'position', 'name', 'country',
                    'odds', 'probability')

data$date <- parse_date_time(data$date, '%Y%m%d%H%M%S')
data$nameCountry <- paste(data$name, " (", data$country, ")", sep="")

# create list of those with more than 5% probability at any point
keep <- unique(data[data$probability >= .1, ]$name)
leaders <- data[data$name %in% keep, ]

# create the plot
p <- ggplot(leaders, aes(date, probability))

png('popeOdds.png', width = 1024, height = 720)
p + geom_line(aes(colour = nameCountry, colour=nameCountry)) +
  theme_bw() +
  scale_y_continuous(limits = c(0,max(leaders$probability + .05)),
                     breaks = seq(0,1,.05)) +
  labs(title = 'Probability of Being the Next Pope',
       x = '',
       y = '') +
  theme(legend.title = element_blank(),
        legend.position = 'bottom',
        legend.key = element_blank(),
        plot.title = element_text(face = 'bold'))
dev.off()

